services:
  stt-whisper-service:
    build: 
      context: .
    env_file: 
      - "../.env.generated"
    environment:
      - STT_WHISPER_SERVICE_DEVICE=cpu
    volumes: 
      - "../sentiric-certificates:/sentiric-certificates:ro"
      - "stt_whisper_cache:/app/model-cache"
    ports: 
      - "15030:15030"
    networks:
      sentiric-net:
        ipv4_address: 10.88.50.3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15030/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  stt_whisper_cache:

networks:
  sentiric-net:
    external: true
    name: sentiric.cloud